// US states data (used as a fallback if API fails)
export const usaStatesData = [
  { stateId: 'AL', name: 'Alabama' },
  { stateId: 'AK', name: 'Alaska' },
  { stateId: 'AZ', name: 'Arizona' },
  { stateId: 'AR', name: 'Arkansas' },
  { stateId: 'CA', name: 'California' },
  { stateId: 'CO', name: 'Colorado' },
  { stateId: 'CT', name: 'Connecticut' },
  { stateId: 'DE', name: 'Delaware' },
  { stateId: 'FL', name: 'Florida' },
  { stateId: 'GA', name: 'Georgia' },
  { stateId: 'HI', name: 'Hawaii' },
  { stateId: 'ID', name: 'Idaho' },
  { stateId: 'IL', name: 'Illinois' },
  { stateId: 'IN', name: 'Indiana' },
  { stateId: 'IA', name: 'Iowa' },
  { stateId: 'KS', name: 'Kansas' },
  { stateId: 'KY', name: 'Kentucky' },
  { stateId: 'LA', name: 'Louisiana' },
  { stateId: 'ME', name: 'Maine' },
  { stateId: 'MD', name: 'Maryland' },
  { stateId: 'MA', name: 'Massachusetts' },
  { stateId: 'MI', name: 'Michigan' },
  { stateId: 'MN', name: 'Minnesota' },
  { stateId: 'MS', name: 'Mississippi' },
  { stateId: 'MO', name: 'Missouri' },
  { stateId: 'MT', name: 'Montana' },
  { stateId: 'NE', name: 'Nebraska' },
  { stateId: 'NV', name: 'Nevada' },
  { stateId: 'NH', name: 'New Hampshire' },
  { stateId: 'NJ', name: 'New Jersey' },
  { stateId: 'NM', name: 'New Mexico' },
  { stateId: 'NY', name: 'New York' },
  { stateId: 'NC', name: 'North Carolina' },
  { stateId: 'ND', name: 'North Dakota' },
  { stateId: 'OH', name: 'Ohio' },
  { stateId: 'OK', name: 'Oklahoma' },
  { stateId: 'OR', name: 'Oregon' },
  { stateId: 'PA', name: 'Pennsylvania' },
  { stateId: 'RI', name: 'Rhode Island' },
  { stateId: 'SC', name: 'South Carolina' },
  { stateId: 'SD', name: 'South Dakota' },
  { stateId: 'TN', name: 'Tennessee' },
  { stateId: 'TX', name: 'Texas' },
  { stateId: 'UT', name: 'Utah' },
  { stateId: 'VT', name: 'Vermont' },
  { stateId: 'VA', name: 'Virginia' },
  { stateId: 'WA', name: 'Washington' },
  { stateId: 'WV', name: 'West Virginia' },
  { stateId: 'WI', name: 'Wisconsin' },
  { stateId: 'WY', name: 'Wyoming' },
  { stateId: 'DC', name: 'District of Columbia' }
];
