// US states data (used as a fallback if API fails)
export const usaStatesData = [
  { id: 1, stateId: 'AL', name: 'Alabama' },
  { id: 2, stateId: 'AK', name: 'Alaska' },
  { id: 3, stateId: 'AZ', name: 'Arizona' },
  { id: 4, stateId: 'AR', name: 'Arkansas' },
  { id: 5, stateId: 'CA', name: 'California' },
  { id: 6, stateId: 'CO', name: 'Colorado' },
  { id: 7, stateId: 'CT', name: 'Connecticut' },
  { id: 8, stateId: 'DE', name: 'Delaware' },
  { id: 9, stateId: 'FL', name: 'Florida' },
  { id: 10, stateId: 'GA', name: 'Georgia' },
  { id: 11, stateId: 'HI', name: 'Hawaii' },
  { id: 12, stateId: 'ID', name: 'Idaho' },
  { id: 13, stateId: 'IL', name: 'Illinois' },
  { id: 14, stateId: 'IN', name: 'Indiana' },
  { id: 15, stateId: 'IA', name: 'Iowa' },
  { id: 16, stateId: 'KS', name: 'Kansas' },
  { id: 17, stateId: 'KY', name: 'Kentucky' },
  { id: 18, stateId: 'LA', name: 'Louisiana' },
  { id: 19, stateId: 'ME', name: 'Maine' },
  { id: 20, stateId: 'MD', name: 'Maryland' },
  { id: 21, stateId: 'MA', name: 'Massachusetts' },
  { id: 22, stateId: 'MI', name: 'Michigan' },
  { id: 23, stateId: 'MN', name: 'Minnesota' },
  { id: 24, stateId: 'MS', name: 'Mississippi' },
  { id: 25, stateId: 'MO', name: 'Missouri' },
  { id: 26, stateId: 'MT', name: 'Montana' },
  { id: 27, stateId: 'NE', name: 'Nebraska' },
  { id: 28, stateId: 'NV', name: 'Nevada' },
  { id: 29, stateId: 'NH', name: 'New Hampshire' },
  { id: 30, stateId: 'NJ', name: 'New Jersey' },
  { id: 31, stateId: 'NM', name: 'New Mexico' },
  { id: 32, stateId: 'NY', name: 'New York' },
  { id: 33, stateId: 'NC', name: 'North Carolina' },
  { id: 34, stateId: 'ND', name: 'North Dakota' },
  { id: 35, stateId: 'OH', name: 'Ohio' },
  { id: 36, stateId: 'OK', name: 'Oklahoma' },
  { id: 37, stateId: 'OR', name: 'Oregon' },
  { id: 38, stateId: 'PA', name: 'Pennsylvania' },
  { id: 39, stateId: 'RI', name: 'Rhode Island' },
  { id: 40, stateId: 'SC', name: 'South Carolina' },
  { id: 41, stateId: 'SD', name: 'South Dakota' },
  { id: 42, stateId: 'TN', name: 'Tennessee' },
  { id: 43, stateId: 'TX', name: 'Texas' },
  { id: 44, stateId: 'UT', name: 'Utah' },
  { id: 45, stateId: 'VT', name: 'Vermont' },
  { id: 46, stateId: 'VA', name: 'Virginia' },
  { id: 47, stateId: 'WA', name: 'Washington' },
  { id: 48, stateId: 'WV', name: 'West Virginia' },
  { id: 49, stateId: 'WI', name: 'Wisconsin' },
  { id: 50, stateId: 'WY', name: 'Wyoming' },
  { id: 51, stateId: 'DC', name: 'District of Columbia' }
];
